language: python
python:
- 3.6
- 3.7
sudo: false
cache:
  directories:
  - eggs
matrix:
  fast_finish: true
install:
- pip install -r requirements.txt
- buildout annotate
- buildout -Nq
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage
- pip install -q coveralls
- coveralls
